#!/bin/bash

function 01_zsh_load()
{
    check_git_clone http://github.com/robbyrussell/oh-my-zsh.git  $HOME/.oh-my-zsh

    check_install zsh "zsh --version"  "sudo apt-get install zsh -y"

    check_ln $HOME/.dotfiles/scripts/ $HOME/scripts
    check_ln $HOME/.dotfiles/zsh/.zshrc $HOME/.zshrc
    check_ln $HOME/.dotfiles/zsh/themes/scastro.zsh-theme $HOME/.oh-my-zsh/themes/scastro.zsh-theme
    
    if [[ "$SHELL" != "/bin/zsh" ]]; then
        chsh -s /usr/bin/zsh
    fi
}
